# Generated by Django 3.1.2 on 2022-02-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(verbose_name='основной')),
            ],
            options={
                'verbose_name_plural': 'Выбор тега',
                'ordering': ['-is_main'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'элемент', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.CreateModel(
            name='ThematicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('article_tag', models.ManyToManyField(through='articles.TagsRelation', to='articles.Article')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='tagsrelation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AddField(
            model_name='tagsrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.thematictag', verbose_name='имя тега'),
        ),
        migrations.AlterUniqueTogether(
            name='tagsrelation',
            unique_together={('article', 'tag')},
        ),
    ]
